[package]
name = "rust"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.7.4", features = ["macros"] }
hyper = { version = "1.0", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shuttle-runtime = "0.39.0"
shuttle-axum = "0.39.0"
tracing = "0.1"
once_cell = "1.19.0"
base64 = "0.21"
uuid = { version = "1.7", features = ["v4", "serde"] }
reqwest = { version = "0.11", features = ["json"] }

[dev-dependencies]
anyhow = "1.0"
httpc-test = "0.1.1"

[[bin]]
name = "rust"
path = "src/main.rs"

[features]
default = []
shuttle = []

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
