[package]
name = "rust"
version = "1.6.0"
authors = ["eooce"]
edition = "2021"

[dependencies]
once_cell = "1.19.0"
hyper = { version = "0.14.9", features = ["full"] }
tokio = { version = "1", features = ["full"] }
shuttle-runtime = "0.39.0"
shuttle-axum = "0.39.0"
axum = "0.7.4"

[[bin]]
name = "rust"
path = "main.rs"
