[package]
name = "rust"
version = "1.6.0"
authors = ["eooce"]
edition = "2021"

[dependencies]
shuttle-runtime = "0.40.0"
shuttle-axum = "0.40.0"
axum = "0.7.1"
tokio = { version = "1.0", features = ["full"] }
once_cell = "1.19.0"
hyper = { version = "0.14.9", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["fs"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "rust"
path = "src/main.rs"
