[package]
name = "rust-shuttle-app"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-runtime = "0.34.1"
shuttle-axum = "0.34.1"
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "0.14.9", features = ["full"] }
once_cell = "1.19.0"
axum = "0.7.2"
