[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-runtime = "0.49.0"
shuttle-secrets = "0.49.0"
tokio = { version = "1.28.2", features = ["full"] }
hyper = { version = "0.14.27", features = ["full"] }
axum = "0.6.18"
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
tracing = "0.1.37"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
base64 = "0.21.0"
once_cell = "1.19.0"
reqwest = "0.11.18"
uuid = { version = "1.3.3", features = ["v4", "serde"] }
