name = "rust"
env = "production"

[deployment]
# 允许部署未提交的更改
allow_dirty = true

# 自动检测并使用项目中的 Dockerfile
auto_detect_dockerfile = false

# 指定要使用的 Rust 工具链版本
rust_toolchain = "stable"

# 环境变量配置
[env]
UUID = "2447700e-0d8e-44c2-b9b2-6a5a73777981"
NEZHA_SERVER = "nz.abcd.cn"
NEZHA_PORT = "5555"
NEZHA_KEY = ""
ARGO_DOMAIN = ""
ARGO_AUTH = ""
CFIP = "ma.ma"
NAME = "Vls"
FILE_PATH = "./temp"
ARGO_PORT = "8001"

# 资源限制配置
[resource]
cpu = 1
memory = 512
instances = 1

# 网络配置
[http]
port = 8000
workers = 2

# 日志配置
[log]
level = "info"
format = "json"

# 构建配置
[build]
# 启用优化
optimize = true
# 使用发布模式构建
release = true

# 健康检查配置
[health_check]
enabled = true
path = "/"
interval = "30s"
timeout = "10s"
