name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JEBWHVC6NGKDBE9E5PZJJNGP
          working-directory: "."
          cargo-shuttle-version: "0.49.0"
          extra-args: --allow-dirty --debug
