name: Deploy to Shuttle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}  # 使用 deploy-key 替代 shuttle-api-key
          working-directory: "."  # 可选，默认为 "."
          allow-dirty: true      # 允许未提交的更改
          name: "rust"  # 替换为你的项目名称
