name: Deploy to Shuttle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install Shuttle CLI
        run: |
          bash -c "$(curl -sSL https://raw.githubusercontent.com/shuttle-hq/shuttle/main/install.sh)"
        
      - name: Create temp directory
        run: mkdir -p temp
        
      - name: Deploy to Shuttle
        run: |
          cargo shuttle deploy --allow-dirty
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
