name: Deploy to Shuttle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make start.sh executable
        run: chmod +x start.sh
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - uses: shuttle-hq/deploy-action@v2
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJECT_ID }}
          working-directory: "."
          allow-dirty: true
          no-test: true
