name: Shuttle Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup project files
        run: |
          mkdir -p temp
          chmod +x start.sh
      
      - uses: shuttle-hq/deploy-action@v0.4.0
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJECT_ID }}
          working-directory: "."
          cargo-shuttle-version: "0.39.0"
