name: Deploy to Shuttle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - name: Install cargo-shuttle
        run: cargo binstall -y --locked cargo-shuttle
      - name: Login to Shuttle
        run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_API_KEY }}
      - name: Start Shuttle Project
        run: cargo shuttle project start --name your-unique-project-name
      - name: Deploy to Shuttle
        run: cargo shuttle deploy --allow-dirty
