name: Deploy to Shuttle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          name: "rust"
          allow-dirty: true
          working-directory: "."
          secrets: |
            PROJECT_ID=${{ secrets.SHUTTLE_PROJECT_ID }}
