name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Make start.sh executable
        run: chmod +x start.sh
          
      - name: Deploy to Shuttle
        uses: shuttle-hq/deploy-action@v0.4.0
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JEB7DVYG3DVZ607BEPB6W7ER
